# Generated by Django 5.1.6 on 2025-02-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
