# Generated by Django 5.1.6 on 2025-02-22 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gearshare",
            "0003_remove_customeruser_user_profile_delete_businessuser_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_librarian",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="join_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="profiles/default.jpg", upload_to="profiles/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="real_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
