# Generated by Django 4.2.20 on 2025-04-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gearshare", "0006_collection_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="condition",
            field=models.CharField(
                choices=[("Great", "Great"), ("Good", "Good"), ("Used", "Used")],
                default="Good",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
