# Generated by Django 4.2.20 on 2025-04-14 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gearshare', '0008_alter_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearshare.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearshare.profile')),
            ],
        ),
    ]
