# Generated by Django 4.2.20 on 2025-04-14 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gearshare', '0009_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearshare.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearshare.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
