# Generated by Django 4.2.20 on 2025-04-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gearshare', '0010_borrowrequest_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gearshare.profile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('being_repaired', 'Being Repaired')], default='checked_in', max_length=20),
        ),
    ]
