# Generated by Django 4.2.20 on 2025-04-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gearshare", "0011_borrowrequest_due_date_borrowrequest_is_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="identifier",
        ),
        migrations.AddField(
            model_name="item",
            name="barcode",
            field=models.ImageField(blank=True, upload_to="barcodes/"),
        ),
    ]
