# Generated by Django 4.2.20 on 2025-04-28 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gearshare', '0011_item_user_alter_item_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearshare.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearshare.profile')),
            ],
        ),
    ]
