# Generated by Django 4.2.20 on 2025-04-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gearshare", "0012_remove_item_identifier_item_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("item", "user")},
        ),
    ]
