# Generated by Django 4.2.20 on 2025-04-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gearshare', '0012_collectionrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionrequest',
            unique_together={('user', 'collection')},
        ),
    ]
