# Generated by Django 4.2.20 on 2025-04-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearshare', '0013_alter_collectionrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='requested_users',
            field=models.ManyToManyField(blank=True, related_name='requested_collections', to='gearshare.profile'),
        ),
    ]
