# Generated by Django 4.2.20 on 2025-04-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gearshare", "0013_rating_updated_at_alter_rating_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
