# Generated by Django 4.2.20 on 2025-04-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gearshare", "0014_collection_last_updated"),
        ("gearshare", "0014_collection_requested_users"),
    ]

    operations = []
