# Generated by Django 4.2.20 on 2025-04-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gearshare", "0016_borrowrequest_requested_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="credit_score",
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
