# Generated by Django 4.2.20 on 2025-04-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gearshare", "0017_profile_credit_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="overdue_processed",
            field=models.BooleanField(default=False),
        ),
    ]
