# Generated by Django 4.2.20 on 2025-04-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gearshare", "0018_item_overdue_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
