# Generated by Django 4.2.20 on 2025-04-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gearshare", "0020_alter_borrowrequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrequest",
            name="agreement_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="borrowrequest",
            name="agreement_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
