# Generated by Django 4.2.20 on 2025-04-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gearshare", "0016_notifications"),
        ("gearshare", "0021_borrowrequest_agreement_accepted_and_more"),
    ]

    operations = []
