# Generated by Django 4.2.20 on 2025-04-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gearshare", "0022_merge_20250429_1724"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="https://gearshare-2025swe-bucket.s3.us-east-2.amazonaws.com/images/default.jpg",
                upload_to="profiles/",
            ),
        ),
    ]
