# Generated by Django 4.2.20 on 2025-04-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gearshare", "0023_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="profiles/default.jpg", upload_to="profiles/"
            ),
        ),
    ]
